### ISSUE TITLE
where is twitchid 

### ISSUE THREAD

**Issue by Kralmanis** [post04/twitch-acc-gen#4]
help meee
what is twitchid
![image](https://user-images.githubusercontent.com/83515130/124926622-6b539f00-e006-11eb-8ec2-8b2386663148.png)

**Comment by Kralmanis** [comment]
![image](https://user-images.githubusercontent.com/83515130/124927438-53c8e600-e007-11eb-95ec-159b1360d3ce.png)

**Comment by post04** [comment]
https://github.com/post04/twitch-acc-gen#how-to-use
