### ISSUE TITLE
Method not allowed

### ISSUE THREAD

**Issue by SrR0b0t** [post04/twitch-acc-gen#6]
I am getting an error while trying to register accounts and I would need some help here.
The error message:
```
Post "https://passport.twitch.tv/register": Method Not Allowed
err at step 2
oauth resp err invalid character 'e' looking for beginning of value
```

I guess "Method not allowed"  means that the POST request to the register URL is failing because of 405 error. 
But this is pretty strange because when I check the network in the chrome devtools while creating a new account manually, it creates a POST request to that exact endpoint. 

Did you experience that issue before?

**Comment by post04** [comment]
I personally don't experience this, I suggest adding debugging and/or using httpdebuggerpro to look at what's actually happening behind the scenes. I can say as of about 3 weeks ago I did test it and it was working.

**Comment by SrR0b0t** [comment]
Seemed to be a proxy issue. Works fine with a different proxy.
I am going to add a proxy list functionality, because twitch throttles the IP after a few accounts (error: ip associated with signup throttled).
